# -*- coding: utf-8 -*-
"""business_model_comp

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hJz-_z3-zJ3x1x2rxi6f8ld4vnP_FtLj
"""

# -*- coding: utf-8 -*-

import matplotlib.pyplot as plt
import json
import os
from datetime import datetime

DIVIDER = "-" * 60


# =========================
# HELPER FUNCTIONS
# =========================

def get_float(prompt, min_value=None, example=None):
    if example:
        print(f"   Example: {example}")
    while True:
        try:
            raw = input(prompt).strip().replace("€", "").replace("$", "").replace(",", "")
            value = float(raw)
            if min_value is not None and value < min_value:
                print(f"   ⚠️  Please enter a number of at least {min_value}. Try again.")
                continue
            return value
        except ValueError:
            print("   ⚠️  That's not a valid number. Please type digits only, e.g. 3.50")


def get_int(prompt, min_value=0, example=None):
    if example:
        print(f"   Example: {example}")
    while True:
        try:
            raw = input(prompt).strip().replace(",", "")
            value = int(raw)
            if value < min_value:
                print(f"   ⚠️  Please enter a whole number of at least {min_value}. Try again.")
                continue
            return value
        except ValueError:
            print("   ⚠️  That's not a valid whole number. Please type digits only, e.g. 300")


def get_yes_no(prompt):
    while True:
        answer = input(prompt + " (type y for yes or n for no): ").strip().lower()
        if answer in ("y", "yes"):
            return True
        if answer in ("n", "no"):
            return False
        print("   ⚠️  Please type 'y' or 'n'.")


def currency(value):
    return f"${value:,.2f}"


def percent(value):
    return f"{value * 100:.1f}%"


def print_header(title):
    print("\n" + "=" * 60)
    print(title)
    print("=" * 60)


def print_note(text):
    print(f"ℹ️  {text}")


# =========================
# WELCOME
# =========================

print_header("WELCOME TO YOUR BUSINESS FINANCIAL MODEL")
print("This tool will ask you simple questions about your business and")
print("calculate revenue, profit, break-even point, risk, and taxes.")
print("You do NOT need any accounting knowledge. Just follow the steps.")
print("\nWe will use a COFFEE SHOP as an example throughout, to help you")
print("understand what kind of answer is expected at each question.")

owner_name = input("\nWhat is your name (or your business name)? ").strip()
if not owner_name:
    owner_name = "Business Owner"

print_header("QUICK GLOSSARY — WORDS YOU'LL SEE IN THIS TOOL")
print("You'll see these words later. Here's what they mean in plain English:\n")
print("  Revenue        = All the money coming IN from sales (before any costs)")
print("  Fixed Costs    = Bills you pay every month no matter what (rent, internet...)")
print("  Variable Cost  = Cost to make ONE unit of a product (ingredients, packaging)")
print("  Profit         = Money left after ALL costs are paid (Revenue − Costs)")
print("  Break-even     = The sales level where you stop losing money (Profit = $0)")
print("  Margin         = What % of a sale you actually KEEP as profit")
print("  Cash Flow      = Money left in the bank after paying everything this month")
print("  Risk Score     = A 0-100 score showing how close you are to financial trouble")
print("\nYou don't need to memorize these — we'll remind you again when they appear.")


# =========================
# STEP 1 — FIXED COSTS (itemized)
# =========================

print_header("STEP 1: YOUR FIXED MONTHLY COSTS")
print("Fixed costs are the bills you pay every month NO MATTER how much")
print("you sell — rent, electricity, water, internet, insurance, your")
print("accountant, software subscriptions, license fees, etc.")
print("\nYou will enter them ONE AT A TIME. This is more accurate than")
print("guessing one big number, and it's easy — just keep adding costs")
print("until you're done.")
print(DIVIDER)

fixed_cost_items = []
while True:
    fixed_cost_items = []
    while True:
        print(f"\nFixed costs entered so far: {len(fixed_cost_items)}  "
              f"(running total: {currency(sum(c for _, c in fixed_cost_items))})")
        name = input("Type the NAME of a fixed cost (e.g. Rent, Electricity) "
                      "or type 'done' if you have entered them all: ").strip()
        if name.lower() in ("done", "finish", "stop", ""):
            if not fixed_cost_items:
                print("   ⚠️  You need to enter at least one fixed cost (even Rent = 0 if you have none).")
                continue
            break
        amount = get_float(f"   How much do you pay per month for '{name}'? $: ",
                            min_value=0, example="Rent = 800, Electricity = 120, Internet = 40")
        fixed_cost_items.append((name, amount))

    print("\nHere's what you entered:")
    for name, amount in fixed_cost_items:
        print(f"   - {name}: {currency(amount)}")
    print(f"   TOTAL: {currency(sum(a for _, a in fixed_cost_items))}")

    if get_yes_no("\nIs this correct? If you made a mistake, we can redo this whole list"):
        break
    print("\nNo problem — let's redo the fixed costs list from scratch.")

fixed_costs = sum(amount for _, amount in fixed_cost_items)

print(f"\n✅ Total Fixed Costs: {currency(fixed_costs)}")
for name, amount in fixed_cost_items:
    print(f"   - {name}: {currency(amount)}")


# =========================
# STEP 2 — PRODUCTS / SERVICES (itemized)
# =========================

print_header("STEP 2: WHAT YOU SELL (PRODUCTS OR SERVICES)")
print("Now enter EACH different thing you sell, one at a time.")
print("For a coffee shop this could be: Espresso, Cappuccino, Cocktail,")
print("Beer, Sandwich, etc. Enter each one separately — do NOT lump them")
print("together — this is what lets the tool show you which products")
print("actually make you money.")
print(DIVIDER)
print("For EACH product, you will answer 3 questions:")
print("  1) The price you SELL it for (what the customer pays)")
print("  2) The cost to YOU to make ONE of it (add up every ingredient/")
print("     packaging item that goes into ONE unit — e.g. for a")
print("     Cappuccino: coffee + milk + cup + lid + sugar = maybe $0.80)")
print("  3) How many you sell per month (your best estimate is fine)")

products = []
while True:
    products = []
    while True:
        print(f"\nProducts entered so far: {len(products)}")
        name = input("Type the NAME of a product/service (e.g. Cappuccino) "
                      "or type 'done' if you have entered them all: ").strip()
        if name.lower() in ("done", "finish", "stop", ""):
            if not products:
                print("   ⚠️  You need to enter at least one product before continuing.")
                continue
            break

        price = get_float(f"   Selling price of ONE '{name}' (what the customer pays) $: ",
                           min_value=0.01, example="Cappuccino sells for $3.50")
        var_cost = get_float(
            f"   Cost to YOU to make ONE '{name}' (ingredients + packaging combined) $: ",
            min_value=0,
            example="Coffee + milk + cup + lid + sugar = $0.80"
        )
        while var_cost >= price:
            print("   ⚠️  Your cost to make it is the same or higher than the price you sell it for.")
            print("      That means you LOSE money every time you sell this item. Please re-check.")
            price = get_float(f"   Re-enter the selling price of ONE '{name}' $: ", min_value=0.01)
            var_cost = get_float(f"   Re-enter the cost to make ONE '{name}' $: ", min_value=0)

        units = get_int(f"   How many '{name}' do you sell per MONTH? ",
                         min_value=0, example="300 cappuccinos a month")

        products.append({"name": name, "price": price, "var_cost": var_cost, "units": units})

    print("\nHere's what you entered:")
    for p in products:
        print(f"   - {p['name']}: sells for {currency(p['price'])}, "
              f"costs {currency(p['var_cost'])} to make, {p['units']} sold/month")

    if get_yes_no("\nIs this correct? If you made a mistake, we can redo this whole list"):
        break
    print("\nNo problem — let's redo the products list from scratch.")


# =========================
# STEP 3 — EMPLOYEES (itemized)
# =========================

print_header("STEP 3: YOUR EMPLOYEES")
print("Enter the monthly salary of EACH employee, one at a time.")
print("If you have no employees, just type 'done' right away.")
print(DIVIDER)

employee_salaries = []
while True:
    print(f"\nEmployees entered so far: {len(employee_salaries)}")
    answer = input("Type an employee's MONTHLY salary in $ (or type 'done' if finished / no employees): ").strip()
    if answer.lower() in ("done", "finish", "stop", ""):
        break
    try:
        salary = float(answer.replace("$", "").replace(",", ""))
        if salary < 0:
            print("   ⚠️  Salary can't be negative.")
            continue
        employee_salaries.append(salary)
    except ValueError:
        print("   ⚠️  Please type a number, or 'done' if finished.")

employees = len(employee_salaries)
base_payroll = sum(employee_salaries)

print(f"\n✅ Total Employees: {employees}")
print(f"✅ Total Base Payroll: {currency(base_payroll)}")

employer_contribution_rate = 0.0
if employees > 0:
    has_contributions = get_yes_no(
        "\nDoes your business pay an extra employer contribution on top of salaries "
        "(e.g. social security / national insurance the EMPLOYER pays, not the employee)"
    )
    if has_contributions:
        employer_contribution_rate = get_float(
            "Enter that employer contribution rate, as a % of salary "
            "(ask your accountant or payroll provider if unsure): ",
            min_value=0,
            example="A common range internationally is 10-25%, but it varies by country"
        ) / 100

employee_costs = base_payroll * (1 + employer_contribution_rate)

if employer_contribution_rate > 0:
    print(f"✅ Employer Contributions ({percent(employer_contribution_rate)}): "
          f"{currency(employee_costs - base_payroll)}")
    print(f"✅ Total Payroll Cost (salaries + employer contributions): {currency(employee_costs)}")


# =========================
# STEP 3B — SUPPLIERS (itemized)
# =========================

print_header("STEP 3B: YOUR SUPPLIERS")
print("Small businesses usually don't know the EXACT cost per unit down to")
print("the cent — but they DO know how much they pay each supplier per")
print("month. This section captures that, supplier by supplier, so costs")
print("that go through different suppliers don't get lost or lumped together.")
print("\nIMPORTANT: If you already included ingredient/product costs per unit")
print("in STEP 2, only use this section for costs NOT already counted there")
print("(e.g. a packaging supplier, cleaning supplies, a separate raw material")
print("supplier). If you're not sure, it's safer to skip this section")
print("(type 'done' right away) than to double-count.")
print(DIVIDER)

supplier_items = []
while True:
    supplier_items = []
    while True:
        print(f"\nSuppliers entered so far: {len(supplier_items)}  "
              f"(running total: {currency(sum(a for _, a in supplier_items))})")
        name = input("Type the NAME of a supplier (e.g. 'Coffee Bean Co', 'Packaging Ltd') "
                      "or type 'done' if you have entered them all / have none: ").strip()
        if name.lower() in ("done", "finish", "stop", ""):
            break
        amount = get_float(f"   How much do you pay '{name}' per MONTH, on average $: ",
                            min_value=0, example="A coffee bean supplier might cost $600/month")
        supplier_items.append((name, amount))

    if supplier_items:
        print("\nHere's what you entered:")
        for name, amount in supplier_items:
            print(f"   - {name}: {currency(amount)}/month")
        print(f"   TOTAL: {currency(sum(a for _, a in supplier_items))}/month")
    else:
        print("\nNo suppliers entered — that's fine if you already counted these costs in STEP 2.")

    if get_yes_no("\nIs this correct? If you made a mistake, we can redo this whole list"):
        break
    print("\nNo problem — let's redo the suppliers list from scratch.")

supplier_costs = sum(amount for _, amount in supplier_items)

if supplier_costs > 0:
    print(f"\n✅ Total Monthly Supplier Costs: {currency(supplier_costs)}")
    for name, amount in supplier_items:
        print(f"   - {name}: {currency(amount)}")


# =========================
# STEP 4 — CASH RESERVE
# =========================

print_header("STEP 4: YOUR CASH RESERVE")
print("This is the money your business currently has available right now")
print("in the bank — your safety cushion if a month goes badly.")
print(DIVIDER)

cash_reserve = get_float("How much cash does your business currently have $: ",
                          min_value=0, example="5,000 in the business bank account")


# =========================
# STEP 4B — OPTIONAL ADVANCED COSTS
# =========================

print_header("STEP 4B: OPTIONAL — MORE ACCURATE NUMBERS (SKIP IF UNSURE)")
print("These next few questions are all OPTIONAL. Skip any you don't know —")
print("the tool works fine without them. Answering them just makes your")
print("numbers more accurate. Each one asks for YOUR OWN rate/number —")
print("we never guess a country's tax rules for you.")
print(DIVIDER)

sales_tax_rate = 0.0
if get_yes_no("\nDo your prices include sales tax / VAT that you have to pay to the "
              "government (not keep as revenue)"):
    sales_tax_rate = get_float(
        "What % of each sale is sales tax / VAT (ask your accountant or check your "
        "country's tax authority if unsure) %: ",
        min_value=0, example="Many countries use rates between 5% and 25%"
    ) / 100

pos_fee_rate = 0.0
if get_yes_no("\nDo you pay a card/POS processing fee or a delivery platform commission "
              "(e.g. Stripe, Square, Uber Eats, Wolt) on your sales"):
    pos_fee_rate = get_float(
        "What % of each sale goes to that fee, on average across all sales %: ",
        min_value=0, example="Card processors are often 1.5-3%, delivery apps often 20-30%"
    ) / 100

waste_rate = 0.0
if get_yes_no("\nDo you lose product to waste, spoilage, or shrinkage "
              "(e.g. unsold food, breakage, theft)"):
    waste_rate = get_float(
        "Roughly what % of your product cost is lost to waste/spoilage %: ",
        min_value=0, example="A rough guess is fine — even 5-10% is common in food businesses"
    ) / 100

monthly_depreciation = 0.0
if get_yes_no("\nDid you buy equipment (oven, fridge, machines, furniture) that you want "
              "to account for as a monthly cost"):
    equipment_cost = get_float("Total cost of the equipment $: ", min_value=0,
                                example="Espresso machine = $4,000")
    useful_life_months = get_int("How many months do you expect it to last: ", min_value=1,
                                  example="Typically 36-84 months (3-7 years)")
    monthly_depreciation = equipment_cost / useful_life_months
    print(f"   → That's {currency(monthly_depreciation)}/month added to your fixed costs.")
    fixed_cost_items.append(("Equipment Depreciation", monthly_depreciation))
    fixed_costs += monthly_depreciation

print("\n✅ Optional costs recorded. On to your financial results.")


# =========================
# STEP 4C — LIQUIDITY SNAPSHOT (for liquidity ratios)
# =========================

print_header("STEP 4C: LIQUIDITY SNAPSHOT (OPTIONAL — SKIP IF UNSURE)")
print("This section is about what you OWE and OWN RIGHT NOW (a snapshot,")
print("not a monthly flow) — it lets the tool calculate liquidity ratios: a")
print("quick check of whether you could cover your short-term bills if")
print("sales stopped tomorrow. Everything here is optional (defaults to 0).")
print(DIVIDER)

owed_to_suppliers = 0.0
if get_yes_no("\nDo you currently have unpaid invoices owed to suppliers (money you "
              "owe them right now, not your monthly spend)"):
    owed_to_suppliers = get_float(
        "How much do you currently owe suppliers in total, right now $: ",
        min_value=0, example="Unpaid invoices adding up to $1,200"
    )

other_current_liabilities = 0.0
if get_yes_no("\nDo you have other short-term debts due within the next 12 months "
              "(e.g. a loan installment, a credit line, unpaid taxes)"):
    other_current_liabilities = get_float(
        "How much is due across all of these in the next 12 months, in total $: ",
        min_value=0, example="A loan repayment schedule totaling $3,000 this year"
    )

accounts_receivable = 0.0
if get_yes_no("\nDo customers currently owe YOU money (unpaid invoices to your business)"):
    accounts_receivable = get_float(
        "How much are customers currently supposed to pay you, in total $: ",
        min_value=0, example="B2B clients who haven't paid yet, totaling $800"
    )

inventory_value = 0.0
if get_yes_no("\nDo you want to include the current value of your stock/inventory"):
    inventory_value = get_float(
        "What is the current value of the stock you have on hand $: ",
        min_value=0, example="Unsold coffee beans, cups, bottles worth $500"
    )

current_assets = cash_reserve + accounts_receivable + inventory_value
current_liabilities = owed_to_suppliers + other_current_liabilities

print(f"\n✅ Current Assets (cash + what's owed to you + stock): {currency(current_assets)}")
print(f"✅ Current Liabilities (what you owe short-term): {currency(current_liabilities)}")


# =========================
# STEP 5 — BASIC FINANCIAL MODEL
# =========================

print_header("STEP 5: YOUR FINANCIAL RESULTS")

gross_revenue = sum(p["price"] * p["units"] for p in products)
sales_tax_remitted = gross_revenue * sales_tax_rate / (1 + sales_tax_rate) if sales_tax_rate > 0 else 0
revenue = gross_revenue - sales_tax_remitted

base_variable_costs = sum(p["var_cost"] * p["units"] for p in products)
waste_cost = base_variable_costs * waste_rate
variable_costs = base_variable_costs + waste_cost

pos_fees = revenue * pos_fee_rate

total_costs = fixed_costs + variable_costs + employee_costs + pos_fees + supplier_costs
profit = revenue - total_costs

if sales_tax_rate > 0 or pos_fee_rate > 0 or waste_rate > 0:
    print("Adjustments applied:")
    if sales_tax_rate > 0:
        print(f"   Gross sales: {currency(gross_revenue)}  →  minus sales tax/VAT owed to "
              f"government ({currency(sales_tax_remitted)})  →  Net Revenue: {currency(revenue)}")
    if waste_rate > 0:
        print(f"   Product costs: {currency(base_variable_costs)}  →  plus {percent(waste_rate)} "
              f"waste/spoilage ({currency(waste_cost)})  →  Total: {currency(variable_costs)}")
    if pos_fee_rate > 0:
        print(f"   POS/delivery fees ({percent(pos_fee_rate)} of revenue): {currency(pos_fees)}")
    print()

print("Per-product breakdown:")
for p in products:
    p_revenue = p["price"] * p["units"]
    p_var_cost = p["var_cost"] * p["units"]
    p_profit_contribution = p_revenue - p_var_cost
    print(f"   - {p['name']}: revenue {currency(p_revenue)}, "
          f"cost {currency(p_var_cost)}, contributes {currency(p_profit_contribution)} "
          f"toward covering fixed costs & profit")

if supplier_items:
    print("\nPer-supplier breakdown:")
    for name, amount in supplier_items:
        share = (amount / revenue * 100) if revenue > 0 else 0
        print(f"   - {name}: {currency(amount)}/month ({share:.1f}% of revenue)")

print(f"\nTotal Revenue:        {currency(revenue)}")
print(f"Total Variable Costs: {currency(variable_costs)}")
print(f"Total Fixed Costs:    {currency(fixed_costs)}")
print(f"Total Supplier Costs: {currency(supplier_costs)}")
print(f"Total Payroll:        {currency(employee_costs)}")
print(f"Total Costs:          {currency(total_costs)}")
print(f"Profit / Loss:        {currency(profit)}")

contribution_margin_ratio = (revenue - variable_costs) / revenue if revenue > 0 else 0
total_fixed_for_breakeven = fixed_costs + employee_costs + supplier_costs

if contribution_margin_ratio > 0:
    break_even_revenue = total_fixed_for_breakeven / contribution_margin_ratio
else:
    break_even_revenue = float("inf")
    print_note("Your products, on average, cost more to make than they sell for. "
               "Break-even is not reachable until this is fixed.")

be_display = "N/A" if break_even_revenue == float("inf") else currency(break_even_revenue)
print(f"\nBreak-even Revenue (you need to sell AT LEAST this much per month "
      f"to cover all costs): {be_display}")


# =========================
# STEP 6 — CASH FLOW & DEATH SPIRAL DETECTOR
# =========================

print_header("STEP 6: CASH FLOW & DEATH SPIRAL DETECTOR")

cash_flow = revenue - total_costs

if cash_flow >= 0:
    months_left = float("inf")
    risk_level_cash = "Low"
else:
    months_left = cash_reserve / abs(cash_flow) if cash_flow != 0 else float("inf")
    if months_left >= 3:
        risk_level_cash = "Medium"
    elif months_left >= 1:
        risk_level_cash = "High"
    else:
        risk_level_cash = "Critical"

months_left_display = "∞ (you have positive cash flow)" if months_left == float("inf") else f"{months_left:,.1f} months"

print(f"Cash Flow (money left after all costs):  {currency(cash_flow)}")
print(f"How long your cash reserve would last if this continued: {months_left_display}")
print(f"Cash Flow Risk Level: {risk_level_cash}")


# =========================
# STEP 7 — PROFIT MARGINS
# =========================

print_header("STEP 7: PROFIT MARGINS")
print("Margins show what % of your sales you actually keep at each stage.")

gross_margin = (revenue - variable_costs) / revenue if revenue > 0 else 0
operating_margin = (revenue - (variable_costs + fixed_costs + employee_costs)) / revenue if revenue > 0 else 0
net_margin = profit / revenue if revenue > 0 else 0

print(f"Gross Margin (after product costs only):        {percent(gross_margin)}")
print(f"Operating Margin (after fixed costs & payroll):  {percent(operating_margin)}")
print(f"Net Margin (your true bottom line):              {percent(net_margin)}")


# =========================
# STEP 8 — RISK OF BANKRUPTCY
# =========================

print_header("STEP 8: RISK OF BANKRUPTCY")

risk_score = (total_costs / revenue) * 100 if revenue > 0 else float("inf")
break_even_health = revenue / break_even_revenue if break_even_revenue not in (0, float("inf")) else 0

if cash_flow >= 0 and risk_score < 80 and break_even_health >= 1:
    combined_risk = "Low"
elif risk_score < 100 and break_even_health >= 0.9:
    combined_risk = "Medium"
elif risk_score < 120 and break_even_health >= 0.75:
    combined_risk = "High"
else:
    combined_risk = "Critical"

print(f"Bankruptcy Risk Score (100 = costs eat all revenue): {risk_score:,.1f} / 100")
print(f"Break-even Health (1.0 = exactly breaking even):     {break_even_health:,.2f}")
print(f"Combined Risk Level:                                 {combined_risk}")


# =========================
# STEP 8B — LIQUIDITY RATIOS
# =========================

print_header("STEP 8B: LIQUIDITY RATIOS")
print("These ratios answer a DIFFERENT question than profit: could you")
print("cover your short-term bills if sales suddenly stopped? A business")
print("can be profitable on paper and still run into trouble here.")

if current_liabilities > 0:
    current_ratio = current_assets / current_liabilities
    quick_ratio = (current_assets - inventory_value) / current_liabilities
    cash_ratio = cash_reserve / current_liabilities
else:
    current_ratio = float("inf")
    quick_ratio = float("inf")
    cash_ratio = float("inf")

working_capital = current_assets - current_liabilities

cr_display = "N/A (no short-term debts entered)" if current_ratio == float("inf") else f"{current_ratio:.2f}"
qr_display = "N/A (no short-term debts entered)" if quick_ratio == float("inf") else f"{quick_ratio:.2f}"
cash_r_display = "N/A (no short-term debts entered)" if cash_ratio == float("inf") else f"{cash_ratio:.2f}"

print(f"\nCurrent Ratio  (Current Assets ÷ Current Liabilities): {cr_display}")
if current_ratio != float("inf"):
    if current_ratio >= 1.5:
        print("   → Healthy: you can comfortably cover short-term debts.")
    elif current_ratio >= 1.0:
        print("   → Tight but okay: you can just about cover short-term debts.")
    else:
        print("   → Warning: your short-term debts are bigger than what you could")
        print("     quickly turn into cash. A bad month could leave you unable to pay.")

print(f"\nQuick Ratio / Acid-Test (excludes inventory): {qr_display}")
if quick_ratio != float("inf"):
    if quick_ratio >= 1.0:
        print("   → Healthy: even without selling your stock, you could cover debts.")
    else:
        print("   → Caution: you're relying on selling inventory to cover short-term debts.")

print(f"\nCash Ratio (cash only — the most conservative test): {cash_r_display}")
if cash_ratio != float("inf"):
    if cash_ratio >= 0.5:
        print("   → Strong: cash alone covers a large share of short-term debts.")
    elif cash_ratio >= 0.2:
        print("   → Okay: some cash cushion, but not huge.")
    else:
        print("   → Thin: very little cash cushion against short-term debts.")

print(f"\nWorking Capital (Current Assets − Current Liabilities): {currency(working_capital)}")
if working_capital < 0:
    print_note("Negative working capital: your short-term debts exceed what you own "
               "short-term. This is a common early-warning sign for cash problems.")


# =========================
# STEP 9 — SCENARIO ANALYSIS
# =========================

print_header("STEP 9: WHAT-IF SCENARIOS")
print("These show what would happen to your business under 3 common situations.")
print("These use the SAME full cost model as your main results — including")
print("supplier costs, POS/delivery fees, waste, and sales tax — so they")
print("stay consistent with the rest of this report.")


def run_scenario(label, price_change=0, sales_change=0, cost_change=0):
    new_gross_revenue = sum(
        p["price"] * (1 + price_change) * p["units"] * (1 + sales_change) for p in products
    )
    new_sales_tax_remitted = (
        new_gross_revenue * sales_tax_rate / (1 + sales_tax_rate) if sales_tax_rate > 0 else 0
    )
    new_revenue = new_gross_revenue - new_sales_tax_remitted

    new_base_variable_costs = sum(
        p["var_cost"] * (1 + cost_change) * p["units"] * (1 + sales_change) for p in products
    )
    new_waste_cost = new_base_variable_costs * waste_rate
    new_variable_costs = new_base_variable_costs + new_waste_cost

    new_pos_fees = new_revenue * pos_fee_rate

    new_total_costs = fixed_costs + new_variable_costs + employee_costs + new_pos_fees + supplier_costs
    new_profit = new_revenue - new_total_costs

    print(f"\n--- Scenario: {label} ---")
    print(f"Revenue:       {currency(new_revenue)}")
    print(f"Total Costs:   {currency(new_total_costs)}")
    print(f"Profit / Loss: {currency(new_profit)}")

    return {"revenue": new_revenue, "total_costs": new_total_costs, "profit": new_profit}


def recalculate_all_scenarios():
    price_up = run_scenario("All prices +10%", price_change=0.10)
    sales_down = run_scenario("Sales -20%", sales_change=-0.20)
    cost_up = run_scenario("Ingredient/product costs +15%", cost_change=0.15)
    return price_up, sales_down, cost_up


scenario_price_up, scenario_sales_down, scenario_cost_up = recalculate_all_scenarios()


# =========================
# STEP 10 — EMPLOYEE & SALARY CALCULATOR
# =========================

print_header("STEP 10: WHAT YOU CAN AFFORD TO PAY STAFF")

available_for_payroll = revenue - (fixed_costs + variable_costs)
avg_salary = employee_costs / employees if employees > 0 else 0

if avg_salary > 0:
    max_employees = available_for_payroll / avg_salary
    max_employees_display = f"{max_employees:,.2f}"
else:
    max_employees_display = "N/A (enter at least one employee to see this)"

max_avg_salary = available_for_payroll / employees if employees > 0 else 0
employee_ratio = employee_costs / revenue if revenue > 0 else 0

print(f"Money available for payroll after fixed & product costs: {currency(available_for_payroll)}")
print(f"Max employees you could afford (at your current average salary): {max_employees_display}")
print(f"Max average salary you could sustainably pay: {currency(max_avg_salary)}")
print(f"Employee Cost Ratio (share of revenue spent on payroll): {percent(employee_ratio)}")


# =========================
# STEP 11 — BUSINESS HEALTH SCORE
# =========================

print_header("STEP 11: OVERALL BUSINESS HEALTH SCORE")
print("A single score from 0 (very unhealthy) to 100 (very healthy),")
print("combining profit, margin, cash flow, break-even, and cost risk.")

profit_score = max(0, min(100, (profit / revenue) * 100)) if revenue > 0 else 0
margin_score = max(0, min(100, net_margin * 100))
cashflow_score = 100 if cash_flow > 0 else max(0, 100 - abs(cash_flow))
breakeven_score = max(0, min(100, break_even_health * 100))
risk_score_normalized = max(0, min(100, 100 - risk_score)) if risk_score != float("inf") else 0

health_score = (
    0.25 * profit_score
    + 0.20 * margin_score
    + 0.20 * cashflow_score
    + 0.20 * breakeven_score
    + 0.15 * risk_score_normalized
)

print(f"\nBusiness Health Score: {health_score:,.1f} / 100")
if health_score >= 75:
    print("   → Healthy business.")
elif health_score >= 50:
    print("   → Okay, but there's room to improve.")
elif health_score >= 25:
    print("   → Warning: your business is under financial stress.")
else:
    print("   → Danger: serious financial problems, act now.")


# =========================
# STEP 12 — BUSINESS DOCTOR (PERSONALIZED ACTION PLAN)
# =========================

first_name = owner_name.split()[0] if owner_name else "there"

print_header("STEP 12: BUSINESS DOCTOR — YOUR PERSONAL DIAGNOSIS")
print(f"{first_name}, this section reads YOUR numbers and tells you, in plain")
print("language, what's wrong and what to do about it — like a business")
print("advisor going through your books with you, item by item.")
print(DIVIDER)

if combined_risk == "Critical":
    print(f"\n🔴 {first_name}, this is CRITICAL — your business is losing money and at")
    print("   real risk of failure if nothing changes. Act on this THIS WEEK.")
elif combined_risk == "High":
    print(f"\n🟠 {first_name}, this is HIGH RISK — your business is under serious")
    print("   financial pressure. Act on the points below within a few weeks.")
elif combined_risk == "Medium":
    print(f"\n🟡 {first_name}, use CAUTION — your business is stable for now, but")
    print("   has weak spots. Address these to build a stronger safety margin.")
else:
    print(f"\n🟢 {first_name}, you're in LOW RISK — your business is healthy right now.")
    print("   Keep monitoring these numbers every month so it stays that way.")

actions = []

if cash_flow < 0 and months_left != float("inf") and months_left < 3:
    actions.append({
        "impact": abs(cash_flow) * 100,
        "text": (
            f"🔴 {first_name}, you are losing {currency(abs(cash_flow))} every month, and at that "
            f"rate your cash runs out in about {months_left:,.1f} months. Do this now: cut your "
            f"biggest cost (see below), raise a price, or bring in extra cash — today, not next month."
        )
    })
elif cash_flow < 0:
    actions.append({
        "impact": abs(cash_flow),
        "text": (
            f"🟠 {first_name}, you are losing {currency(abs(cash_flow))} every month. Fix the causes "
            f"listed below before it eats through your reserve."
        )
    })

if break_even_health < 1:
    shortfall = break_even_revenue - revenue if break_even_revenue != float("inf") else 0
    actions.append({
        "impact": shortfall,
        "text": (
            f"🟠 {first_name}, sell {currency(shortfall)} more per month than you do now just to "
            f"stop losing money. Do it with a mix of: raise prices a little, sell more, and cut "
            f"the costs flagged below."
        )
    })

if revenue > 0:
    for name, amount in fixed_cost_items:
        share = amount / revenue
        if share > 0.15:
            actions.append({
                "impact": amount - (0.15 * revenue),
                "text": (
                    f"🟠 {first_name}, your '{name}' costs {currency(amount)}/month — that's "
                    f"{percent(share)} of everything you make. That's too much for one expense. "
                    f"Call your provider and negotiate it down, shop for a cheaper alternative, "
                    f"or cut it if you can."
                )
            })

if revenue > 0:
    for name, amount in supplier_items:
        share = amount / revenue
        if share > 0.15:
            actions.append({
                "impact": amount - (0.15 * revenue),
                "text": (
                    f"🟠 {first_name}, you pay '{name}' {currency(amount)}/month — that's "
                    f"{percent(share)} of everything you make. You're exposed if this supplier "
                    f"raises prices or has problems. Negotiate better terms, or line up a second "
                    f"supplier as backup so you're not fully dependent on one."
                )
            })

if len(supplier_items) == 1 and supplier_costs > 0:
    actions.append({
        "impact": supplier_costs * 0.5,
        "text": (
            f"🟡 {first_name}, you rely on a single supplier for everything you buy in. If they "
            f"run out of stock, raise prices, or shut down, your business stops with them. "
            f"Look for at least one backup supplier, even if you don't use them yet."
        )
    })

if current_liabilities > 0 and current_ratio < 1.0:
    actions.append({
        "impact": (current_liabilities - current_assets) * 10,
        "text": (
            f"🔴 {first_name}, your short-term debts ({currency(current_liabilities)}) are bigger "
            f"than what you could quickly turn into cash ({currency(current_assets)}). This is a "
            f"liquidity risk, separate from profit — even a profitable business can get caught "
            f"out here. Prioritize collecting what customers owe you and slow down new debt."
        )
    })

if gross_margin < 0.30 and revenue > 0:
    target_revenue_for_30pct = variable_costs / 0.70
    extra_revenue_needed = max(0, target_revenue_for_30pct - revenue)
    actions.append({
        "impact": extra_revenue_needed,
        "text": (
            f"🟠 {first_name}, your menu prices are too close to what things cost you to make — "
            f"you only keep {percent(gross_margin)} per sale. Raise prices across the board a "
            f"little, or find a cheaper supplier, to free up about {currency(extra_revenue_needed)}/month."
        )
    })

if employee_ratio > 0.40 and revenue > 0:
    excess_payroll = employee_costs - (0.40 * revenue)
    actions.append({
        "impact": excess_payroll,
        "text": (
            f"🟠 {first_name}, {percent(employee_ratio)} of your revenue goes to staff wages — "
            f"about {currency(excess_payroll)} more than it should be. Look at your weekly "
            f"schedule: are you overstaffed on slow days or shifts?"
        )
    })

suggested_price_changes = []
if products:
    for p in products:
        p_margin = (p["price"] - p["var_cost"]) / p["price"] if p["price"] > 0 else 0
        if p_margin < 0.30:
            target_price = p["var_cost"] / 0.70
            price_increase_needed = max(0, target_price - p["price"])
            monthly_impact = price_increase_needed * p["units"]
            if monthly_impact > 0:
                actions.append({
                    "impact": monthly_impact,
                    "text": (
                        f"🟡 {first_name}, raise the price of '{p['name']}' from "
                        f"{currency(p['price'])} to {currency(target_price)}. It only earns you "
                        f"{percent(p_margin)} right now — that small raise is worth about "
                        f"{currency(monthly_impact)}/month at your current sales volume."
                    )
                })
                suggested_price_changes.append((p, target_price, monthly_impact))

if len(products) > 1:
    best = max(products, key=lambda p: (p["price"] - p["var_cost"]))
    best_margin = (best["price"] - best["var_cost"]) / best["price"] if best["price"] > 0 else 0
    if best_margin > 0.40:
        actions.append({
            "impact": (best["price"] - best["var_cost"]) * best["units"] * 0.10,
            "text": (
                f"🟢 {first_name}, '{best['name']}' is your best earner — {percent(best_margin)} "
                f"margin. Push it: feature it on the menu/counter, suggest it to every customer, "
                f"bundle it with something else. Selling 10% more of it alone is worth about "
                f"{currency((best['price'] - best['var_cost']) * best['units'] * 0.10)}/month."
            )
        })

if cash_reserve == 0 and cash_flow < 0:
    actions.append({
        "impact": abs(cash_flow) * 100,
        "text": (
            f"🔴 {first_name}, you have $0 saved and you're losing money — one bad week could "
            f"sink you. As soon as cash flow turns positive, start putting money aside every "
            f"month before anything else."
        )
    })

actions.sort(key=lambda a: a["impact"], reverse=True)

if actions:
    print(f"\n{first_name}, here's exactly what to do, biggest problem first:\n")
    for i, action in enumerate(actions, start=1):
        print(f"{i}. {action['text']}\n")
else:
    print(f"\n{first_name}, no major red flags right now. Keep checking these numbers every month.")

print_note("Based on your own numbers, not a replacement for a professional who knows your full situation.")


# =========================
# STEP 12B — APPLY SUGGESTED PRICES NOW?
# =========================

if suggested_price_changes:
    print(f"\n{first_name}, I can apply these {len(suggested_price_changes)} suggested price "
          f"change(s) right now and instantly show you the new numbers — nothing is saved "
          f"anywhere else, you can still say no.")
    apply_now = get_yes_no("Apply the suggested prices now and recalculate")

    if apply_now:
        total_added = 0
        for p, new_price, monthly_impact in suggested_price_changes:
            old_price = p["price"]
            p["price"] = round(new_price, 2)
            total_added += monthly_impact
            print(f"   ✅ '{p['name']}': {currency(old_price)} → {currency(p['price'])}")

        gross_revenue = sum(p["price"] * p["units"] for p in products)
        sales_tax_remitted = gross_revenue * sales_tax_rate / (1 + sales_tax_rate) if sales_tax_rate > 0 else 0
        revenue = gross_revenue - sales_tax_remitted
        base_variable_costs = sum(p["var_cost"] * p["units"] for p in products)
        waste_cost = base_variable_costs * waste_rate
        variable_costs = base_variable_costs + waste_cost
        pos_fees = revenue * pos_fee_rate
        total_costs = fixed_costs + variable_costs + employee_costs + pos_fees + supplier_costs
        profit = revenue - total_costs
        contribution_margin_ratio = (revenue - variable_costs) / revenue if revenue > 0 else 0
        total_fixed_for_breakeven = fixed_costs + employee_costs + supplier_costs
        break_even_revenue = (total_fixed_for_breakeven / contribution_margin_ratio
                               if contribution_margin_ratio > 0 else float("inf"))
        be_display = "N/A" if break_even_revenue == float("inf") else currency(break_even_revenue)

        cash_flow = revenue - total_costs
        if cash_flow >= 0:
            months_left = float("inf")
        else:
            months_left = cash_reserve / abs(cash_flow) if cash_flow != 0 else float("inf")
        months_left_display = ("∞ (you have positive cash flow)" if months_left == float("inf")
                                else f"{months_left:,.1f} months")

        gross_margin = (revenue - variable_costs) / revenue if revenue > 0 else 0
        operating_margin = (revenue - (variable_costs + fixed_costs + employee_costs)) / revenue if revenue > 0 else 0
        net_margin = profit / revenue if revenue > 0 else 0

        risk_score = (total_costs / revenue) * 100 if revenue > 0 else float("inf")
        break_even_health = revenue / break_even_revenue if break_even_revenue not in (0, float("inf")) else 0
        if cash_flow >= 0 and risk_score < 80 and break_even_health >= 1:
            combined_risk = "Low"
        elif risk_score < 100 and break_even_health >= 0.9:
            combined_risk = "Medium"
        elif risk_score < 120 and break_even_health >= 0.75:
            combined_risk = "High"
        else:
            combined_risk = "Critical"

        profit_score = max(0, min(100, (profit / revenue) * 100)) if revenue > 0 else 0
        margin_score = max(0, min(100, net_margin * 100))
        cashflow_score = 100 if cash_flow > 0 else max(0, 100 - abs(cash_flow))
        breakeven_score = max(0, min(100, break_even_health * 100))
        risk_score_normalized = max(0, min(100, 100 - risk_score)) if risk_score != float("inf") else 0
        health_score = (
            0.25 * profit_score + 0.20 * margin_score + 0.20 * cashflow_score
            + 0.20 * breakeven_score + 0.15 * risk_score_normalized
        )

        print(f"\n{first_name}, recalculating your what-if scenarios (Step 9) with the new prices too...")
        scenario_price_up, scenario_sales_down, scenario_cost_up = recalculate_all_scenarios()

        print(f"\n{first_name}, here are your UPDATED numbers after the price changes:")
        print(f"   New Revenue:       {currency(revenue)}")
        print(f"   New Profit/Loss:   {currency(profit)}")
        print(f"   New Cash Flow:     {currency(cash_flow)}")
        print(f"   New Risk Level:    {combined_risk}")
        print(f"   New Health Score:  {health_score:,.1f} / 100")
        print(f"   (That's {currency(total_added)}/month more than before, just from these price changes.)")
    else:
        print("   Okay — no prices changed. The numbers below still reflect your original prices.")


# =========================
# STEP 13 — INCOME TAX & NET PROFIT AFTER TAX
# =========================

print_header("STEP 13: INCOME TAX & NET PROFIT AFTER TAX")
print("Tax rules are different in every country, region, and business type,")
print("so this tool will NOT guess a number for you — that could be wrong")
print("and mislead you. Instead, enter the tax rate that applies to YOUR")
print("business, in YOUR country. If you don't know it, ask your")
print("accountant or check your local tax authority's website.")
print_note("This is an ESTIMATE for planning only — not tax advice.")

include_tax = get_yes_no("\nDo you want to calculate tax now")

income_tax_rate = 0.0
self_employment_tax_rate = 0.0
tax_amount = 0.0
self_employment_tax_amount = 0.0
net_profit_after_tax = profit

if include_tax:
    income_tax_rate = get_float(
        "Enter YOUR income/business tax rate (combined, e.g. federal+state) in %: ",
        min_value=0,
        example="If you don't know it, check with your accountant or tax authority"
    ) / 100

    include_se_tax = get_yes_no(
        "Do you also pay a self-employment / social security style tax on profit "
        "(e.g. ~15.3% in the US for sole proprietors)"
    )
    if include_se_tax:
        self_employment_tax_rate = get_float(
            "Enter that self-employment/social security tax rate in %: ", min_value=0
        ) / 100

    if profit > 0:
        self_employment_tax_amount = profit * self_employment_tax_rate
        taxable_profit = profit - self_employment_tax_amount
        tax_amount = taxable_profit * income_tax_rate
        net_profit_after_tax = profit - self_employment_tax_amount - tax_amount
    else:
        print_note("You have a loss this month, so no tax is due in this simplified model.")

    print(f"\nIncome Tax Rate Used:       {percent(income_tax_rate)}")
    if self_employment_tax_rate > 0:
        print(f"Self-Employment Tax Rate:   {percent(self_employment_tax_rate)}")
        print(f"Self-Employment Tax Amount: {currency(self_employment_tax_amount)}")
    print(f"Income Tax Amount:          {currency(tax_amount)}")
    print(f"Net Profit After Tax:       {currency(net_profit_after_tax)}")
else:
    print("\nSkipping tax. Net Profit After Tax = Profit before tax.")

print_note("Always confirm exact tax figures with a licensed accountant in your country.")


# =========================
# STEP 14 — CHARTS
# =========================

print_header("STEP 14: CHARTS")
print("Generating charts...")

if break_even_revenue != float("inf"):
    max_x = max(revenue, break_even_revenue) * 1.5
else:
    max_x = revenue * 1.5 if revenue > 0 else 1000

x_values = [i for i in range(0, int(max_x) + 1, max(1, int(max_x // 100)))]
revenue_line = x_values
cost_line = [total_fixed_for_breakeven + (1 - contribution_margin_ratio) * x for x in x_values]

plt.figure(figsize=(8, 5))
plt.plot(x_values, revenue_line, label="Revenue", color="#2E8B57", linewidth=2)
plt.plot(x_values, cost_line, label="Total Costs", color="#C0392B", linewidth=2)
if break_even_revenue != float("inf"):
    plt.axvline(break_even_revenue, color="gray", linestyle="--", linewidth=1)
    plt.scatter([break_even_revenue], [break_even_revenue], color="black", zorder=5,
                label=f"Break-even ({currency(break_even_revenue)})")
plt.axvline(revenue, color="#2980B9", linestyle=":", linewidth=1,
            label=f"Your current revenue ({currency(revenue)})")
plt.title("Break-even Chart")
plt.xlabel("Monthly Revenue ($)")
plt.ylabel("Amount ($)")
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("break_even_chart.png", dpi=150)
plt.show()

product_names = [p["name"] for p in products]
product_contributions = [(p["price"] - p["var_cost"]) * p["units"] for p in products]
bar_colors_products = ["#2980B9" if c >= 0 else "#C0392B" for c in product_contributions]

plt.figure(figsize=(8, 5))
bars = plt.bar(product_names, product_contributions, color=bar_colors_products)
plt.axhline(0, color="black", linewidth=0.8)
plt.title("Which Products Make You the Most Money")
plt.ylabel("Monthly Profit Contribution ($)")
plt.xticks(rotation=30, ha="right")
for bar, value in zip(bars, product_contributions):
    plt.text(bar.get_x() + bar.get_width() / 2, value, f"${value:,.0f}",
              ha="center", va="bottom" if value >= 0 else "top")
plt.grid(alpha=0.3, axis="y")
plt.tight_layout()
plt.savefig("product_profitability_chart.png", dpi=150)
plt.show()

scenario_labels = ["Current", "Prices +10%", "Sales -20%", "Costs +15%"]
scenario_profits = [profit, scenario_price_up["profit"], scenario_sales_down["profit"], scenario_cost_up["profit"]]
bar_colors_scenarios = ["#2980B9" if p >= 0 else "#C0392B" for p in scenario_profits]

plt.figure(figsize=(8, 5))
bars = plt.bar(scenario_labels, scenario_profits, color=bar_colors_scenarios)
plt.axhline(0, color="black", linewidth=0.8)
plt.title("Scenario Comparison — Profit / Loss")
plt.ylabel("Profit / Loss ($)")
for bar, value in zip(bars, scenario_profits):
    plt.text(bar.get_x() + bar.get_width() / 2, value, f"${value:,.0f}",
              ha="center", va="bottom" if value >= 0 else "top")
plt.grid(alpha=0.3, axis="y")
plt.tight_layout()
plt.savefig("scenario_comparison_chart.png", dpi=150)
plt.show()

print("✅ Charts saved: break_even_chart.png, product_profitability_chart.png, "
      "scenario_comparison_chart.png")


# =========================
# STEP 15 — FINAL BUSINESS REPORT
# =========================

print_header(f"STEP 15: FINAL BUSINESS REPORT — {owner_name}")

print("FIXED COSTS:")
for name, amount in fixed_cost_items:
    print(f"   - {name}: {currency(amount)}")
print(f"   TOTAL: {currency(fixed_costs)}")

print("\nPRODUCTS:")
for p in products:
    print(f"   - {p['name']}: price {currency(p['price'])}, cost {currency(p['var_cost'])}, "
          f"{p['units']} sold/month")

print(f"\nEMPLOYEES: {employees}  |  Total Payroll: {currency(employee_costs)}")

if supplier_items:
    print("\nSUPPLIERS:")
    for name, amount in supplier_items:
        print(f"   - {name}: {currency(amount)}/month")
    print(f"   TOTAL: {currency(supplier_costs)}/month")

print(f"\nRevenue:                 {currency(revenue)}")
print(f"Total Costs:             {currency(total_costs)}")
print(f"Profit / Loss (pre-tax): {currency(profit)}")
if include_tax:
    print(f"Income Tax:              {currency(tax_amount)}")
    if self_employment_tax_rate > 0:
        print(f"Self-Employment Tax:     {currency(self_employment_tax_amount)}")
    print(f"Net Profit After Tax:    {currency(net_profit_after_tax)}")
print(f"Cash Flow:               {currency(cash_flow)}")
print(f"Months of Reserve Left:  {months_left_display}")
print(f"Break-even Revenue:      {be_display}")
print(f"Bankruptcy Risk Score:   {risk_score:,.1f} / 100")
print(f"Combined Risk Level:     {combined_risk}")
print(f"Business Health Score:   {health_score:,.1f} / 100")
print(f"Current Ratio:           {cr_display}")
print(f"Quick Ratio:             {qr_display}")
print(f"Cash Ratio:              {cash_r_display}")
print(f"Working Capital:         {currency(working_capital)}")

print("\n" + "=" * 60)
print("Thank you for using the Business Financial Model.")
print("=" * 60)


# =========================
# STEP 15B — SAVE REPORT TO FILE
# =========================

print_header("STEP 15B: SAVING YOUR REPORT TO A FILE")

report_filename = f"{owner_name.replace(' ', '_')}_financial_report.txt".lower()

with open(report_filename, "w", encoding="utf-8") as f:
    f.write(f"BUSINESS FINANCIAL REPORT — {owner_name}\n")
    f.write("=" * 60 + "\n\n")

    f.write("FIXED COSTS:\n")
    for name, amount in fixed_cost_items:
        f.write(f"   - {name}: {currency(amount)}\n")
    f.write(f"   TOTAL: {currency(fixed_costs)}\n\n")

    f.write("PRODUCTS:\n")
    for p in products:
        f.write(f"   - {p['name']}: price {currency(p['price'])}, cost {currency(p['var_cost'])}, "
                 f"{p['units']} sold/month\n")

    if supplier_items:
        f.write("\nSUPPLIERS:\n")
        for name, amount in supplier_items:
            f.write(f"   - {name}: {currency(amount)}/month\n")
        f.write(f"   TOTAL: {currency(supplier_costs)}/month\n")

    f.write(f"\nEMPLOYEES: {employees}  |  Total Payroll: {currency(employee_costs)}\n\n")

    f.write(f"Revenue:                 {currency(revenue)}\n")
    f.write(f"Total Costs:             {currency(total_costs)}\n")
    f.write(f"Profit / Loss (pre-tax): {currency(profit)}\n")
    if include_tax:
        f.write(f"Income Tax:              {currency(tax_amount)}\n")
        if self_employment_tax_rate > 0:
            f.write(f"Self-Employment Tax:     {currency(self_employment_tax_amount)}\n")
        f.write(f"Net Profit After Tax:    {currency(net_profit_after_tax)}\n")
    f.write(f"Cash Flow:               {currency(cash_flow)}\n")
    f.write(f"Months of Reserve Left:  {months_left_display}\n")
    f.write(f"Break-even Revenue:      {be_display}\n")
    f.write(f"Bankruptcy Risk Score:   {risk_score:,.1f} / 100\n")
    f.write(f"Combined Risk Level:     {combined_risk}\n")
    f.write(f"Business Health Score:   {health_score:,.1f} / 100\n")
    f.write(f"Current Ratio:           {cr_display}\n")
    f.write(f"Quick Ratio:             {qr_display}\n")
    f.write(f"Cash Ratio:              {cash_r_display}\n")
    f.write(f"Working Capital:         {currency(working_capital)}\n\n")

    f.write("TOP PRIORITIES TO FIX (biggest financial impact first):\n")
    if actions:
        for i, action in enumerate(actions, start=1):
            clean_text = action["text"].encode("ascii", "ignore").decode()
            f.write(f"PRIORITY {i}. {clean_text}\n\n")
    else:
        f.write("No major red flags found. Keep tracking monthly.\n")

    f.write("\nNote: This is a simplified planning tool, not professional financial,\n")
    f.write("tax, or accounting advice. Confirm important decisions with a licensed\n")
    f.write("accountant or advisor in your country.\n")

print(f"\n📄 A full copy of this report has been saved to: {report_filename}")
print("   In Google Colab, find it in the file browser on the left (folder icon),")
print("   or download it from there to keep on your computer.")


# =========================
# STEP 16 — MONTH-OVER-MONTH HISTORY
# =========================

print_header("STEP 16: TRACKING OVER TIME")

history_filename = f"{owner_name.replace(' ', '_')}_history.json".lower()

history = []
if os.path.exists(history_filename):
    try:
        with open(history_filename, "r", encoding="utf-8") as f:
            history = json.load(f)
    except (json.JSONDecodeError, ValueError):
        history = []

if history:
    last = history[-1]
    print(f"Comparing to your last saved run ({last['date']}):\n")

    def show_change(label, old_value, new_value, is_currency=True):
        diff = new_value - old_value
        arrow = "▲" if diff > 0 else ("▼" if diff < 0 else "→")
        diff_display = currency(abs(diff)) if is_currency else f"{abs(diff):,.1f}"
        print(f"   {label}: {currency(old_value) if is_currency else f'{old_value:,.1f}'} "
              f"→ {currency(new_value) if is_currency else f'{new_value:,.1f}'}  "
              f"({arrow} {diff_display})")

    show_change("Revenue", last["revenue"], revenue)
    show_change("Profit / Loss", last["profit"], profit)
    show_change("Health Score", last["health_score"], health_score, is_currency=False)
    print(f"   Risk Level: {last['combined_risk']} → {combined_risk}")
else:
    print(f"{first_name}, this is your first saved run — nothing to compare yet.")
    print("Run this tool again next month with your new numbers, and it will automatically")
    print("show you what improved and what got worse.")

history.append({
    "date": datetime.now().strftime("%Y-%m-%d"),
    "revenue": revenue,
    "profit": profit,
    "cash_flow": cash_flow,
    "health_score": health_score,
    "combined_risk": combined_risk,
})

with open(history_filename, "w", encoding="utf-8") as f:
    json.dump(history, f, indent=2)

print(f"\n📈 This run has been added to your history file: {history_filename}")
print("   Keep this file (download it, or keep it in the same Colab folder) so next time")
print("   you run the tool, it can show you your progress month to month.")